### ISSUE TITLE
Measure execution time of functions

### ISSUE THREAD

**Issue by FlyinPancake** [TanklesXL/gladvent#21]
My friends and I like to ~measure d*cks~ compare the execution times of our AoC solutions.

I'd like to see the execution time of the functions I write in millis or nanos with a flag to run like --exec-time or -E

**Comment by kwando** [comment]
I think it could always be there in the output.

**Comment by TanklesXL** [comment]
i'm not against adding this, and i agree with @kwando that if added it would probably always be present
