### ISSUE TITLE
Use two digit numbers for all days

### ISSUE THREAD

**Issue by giacomocavalieri** [TanklesXL/gladvent#25]
This is a very minor thing and totally reasonable to ignore but it would be so nice if the day files used 0 padded numbers so that everything sorts nicely in editors using alphabetical ordering of files. Right now it looks like this:
<img width="240" alt="Screenshot 2024-12-11 alle 09 42 36" src="https://github.com/user-attachments/assets/f65702f9-decf-465a-bf58-4aba5aaf7020">
If the numbers where `day_01`, `day_02`, ..., `day_10` they would be properly sorted.

**Comment by TanklesXL** [comment]
@giacomocavalieri this is already being tackled in #22

**Comment by TanklesXL** [comment]
closing as redundant 💜
